'use client';

import { useEffect } from 'react';
import { logClientErrorToFirestore } from '@/firebase/system-logger';
import {
  shouldAllow,
  shouldReportError,
  recordOutbound,
  recordError,
} from '@/lib/self-regulation';

type ErrorPayload = {
  message: string;
  stack?: string;
  source?: string;
  line?: number;
  column?: number;
  url?: string;
  userAgent?: string;
  timestamp?: string;
};

const SERVER_ACTION_RECOVERY_MARKER = 'molly:server-action-recovered-at';
const SERVER_ACTION_RECOVERY_COOLDOWN_MS = 30_000;
const FETCH_FAILURE_MESSAGE = 'Failed to fetch';

function shouldAttemptServerActionRecovery(message: string): boolean {
  return (
    message.includes('An unexpected response was received from the server') ||
    (message.includes('Server Action "') &&
      message.includes('was not found on the server'))
  );
}

function recoverFromServerActionMismatch(message: string): void {
  if (
    typeof window === 'undefined' ||
    !shouldAttemptServerActionRecovery(message)
  ) {
    return;
  }

  try {
    const lastRecoveryAt = Number(
      window.sessionStorage.getItem(SERVER_ACTION_RECOVERY_MARKER) || '0'
    );

    if (Date.now() - lastRecoveryAt < SERVER_ACTION_RECOVERY_COOLDOWN_MS) {
      return;
    }

    window.sessionStorage.setItem(
      SERVER_ACTION_RECOVERY_MARKER,
      String(Date.now())
    );
    window.location.reload();
  } catch {
    // If storage is unavailable, we still attempt one direct reload.
    window.location.reload();
  }
}

function shouldSuppressTelemetryEvent(
  message: string,
  details?: string
): boolean {
  if (shouldAttemptServerActionRecovery(message)) {
    // A reload has already been initiated for this transient mismatch.
    return true;
  }

  if (
    message.includes(FETCH_FAILURE_MESSAGE) &&
    (details?.includes('ClientErrorReporter.tsx') ?? false)
  ) {
    // Ignore failures generated by this reporter's own fire-and-forget telemetry.
    return true;
  }

  return false;
}

function sendClientError(payload: ErrorPayload) {
  // Self-regulation: should she report this?
  if (!shouldAllow('error-report')) return;
  if (!shouldReportError(payload.message)) return;

  recordOutbound();
  try {
    void fetch('/api/client-errors', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
      keepalive: true,
    }).catch(() => {
      // Telemetry failures are non-critical and should never recurse.
    });
  } catch {
    // Synchronous fetch setup errors are non-critical.
  }
}

function sendSessionEvent(message: string, details?: string) {
  // Self-regulation: should she send this session event?
  if (!shouldAllow('session-event')) return;

  recordOutbound();
  try {
    void fetch('/api/session/event', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        event: message,
        details,
        url: typeof window !== 'undefined' ? window.location.href : undefined,
        timestamp: new Date().toISOString(),
      }),
      keepalive: true,
    }).catch(() => {
      // Ignore network races during unload/background transitions.
    });
  } catch {
    // Synchronous fetch setup errors are non-critical.
  }
}

export function ClientErrorReporter() {
  useEffect(() => {
    const handleError = (event: ErrorEvent) => {
      // Record the error in self-regulation (she's observing herself)
      recordError();

      const details = event.error?.stack || event.message;
      recoverFromServerActionMismatch(event.message || details);
      if (
        shouldSuppressTelemetryEvent(event.message || 'Unknown error', details)
      ) {
        return;
      }
      sendSessionEvent('client-error', details);
      sendClientError({
        message: event.message || 'Unknown error',
        stack: event.error?.stack,
        source: event.filename,
        line: event.lineno,
        column: event.colno,
        url: window.location.href,
        userAgent: navigator.userAgent,
        timestamp: new Date().toISOString(),
      });

      // Self-regulation: Firestore log only in normal/cautious mode
      if (shouldAllow('firestore-log')) {
        recordOutbound();
        void logClientErrorToFirestore({
          message: event.message || 'Unknown error',
          stack: event.error?.stack,
          source: event.filename,
          line: event.lineno,
          column: event.colno,
          url: window.location.href,
          userAgent: navigator.userAgent,
          timestamp: new Date().toISOString(),
        });
      }
    };

    const handleRejection = (event: PromiseRejectionEvent) => {
      // Record the error in self-regulation
      recordError();

      const reason = event.reason instanceof Error ? event.reason : null;
      const message =
        reason?.message || String(event.reason || 'Unhandled rejection');
      recoverFromServerActionMismatch(message);
      if (shouldSuppressTelemetryEvent(message, reason?.stack)) {
        return;
      }
      sendSessionEvent(
        'unhandled-rejection',
        reason?.stack || String(event.reason || 'Unhandled rejection')
      );
      sendClientError({
        message,
        stack: reason?.stack,
        url: window.location.href,
        userAgent: navigator.userAgent,
        timestamp: new Date().toISOString(),
      });

      // Self-regulation: Firestore log only when allowed
      if (shouldAllow('firestore-log')) {
        recordOutbound();
        void logClientErrorToFirestore({
          message,
          stack: reason?.stack,
          url: window.location.href,
          userAgent: navigator.userAgent,
          timestamp: new Date().toISOString(),
        });
      }
    };

    window.addEventListener('error', handleError);
    window.addEventListener('unhandledrejection', handleRejection);

    return () => {
      window.removeEventListener('error', handleError);
      window.removeEventListener('unhandledrejection', handleRejection);
    };
  }, []);

  return null;
}
