/**
 * @jest-environment node
 *
 * Item 12 (right-hemisphere semantic recall) coverage.
 *
 * Contract under test (per Lazarus's plan, msg 1782211565881):
 *   - MemoryEngram carries `embedding: number[] | null` (optional, lazy)
 *   - recallSemantic() returns [] when no provider is configured (callers
 *     are expected to fall back to substring recall() in that case)
 *   - When a provider is configured, cosine similarity ranks results
 *   - Embeddings are generated lazily on first recall — NOT at write — and
 *     cached on the engram object so subsequent recalls don't re-embed
 *   - Per-engram embed failures are isolated (warn-logged, skipped) and
 *     never poison the rest of the recall
 *   - Both working memory (frontal cortex) and the consolidation queue
 *     (hippocampus) are searched; results are de-duped by engram id
 */

jest.mock('@/ai/logger', () => ({
  MollyLogger: {
    info: jest.fn(),
    warn: jest.fn(),
    error: jest.fn(),
    debug: jest.fn(),
  },
}));

jest.mock('@/ai/memory/engram-persistence', () => ({
  persistEngramBatch: jest
    .fn()
    .mockResolvedValue({ saved: 0, failed: 0, errors: [] }),
  loadConsolidatedEngrams: jest
    .fn()
    .mockResolvedValue({ loaded: 0, failed: 0, errors: [], engrams: [] }),
}));

jest.mock('@/ai/memory/personality-diagnostics', () => ({
  evaluatePersonalityStability: jest.fn().mockReturnValue({
    status: 'stable',
    score: 0.9,
    flags: [],
    extremes: 0,
    variance: 0.1,
  }),
}));

// Symmetric-write target — keep it inert so we don't fight an async path
// we aren't asserting against here.
jest.mock('@/ai/memory/knowledge-store', () => {
  const actual = jest.requireActual('@/ai/memory/knowledge-store');
  return {
    ...actual,
    getKnowledgeStore: jest.fn().mockResolvedValue({
      write: jest.fn().mockResolvedValue(undefined),
      recall: jest.fn().mockResolvedValue([]),
      recordSnapshot: jest.fn().mockResolvedValue(undefined),
    }),
  };
});

import { NeuralEngramSystem } from '../neural-engram';
import {
  setEmbeddingProvider,
  resetEmbeddingProvider,
  type IEmbeddingProvider,
  type EmbeddingResult,
  type BatchEmbeddingResult,
} from '@/ai/tools/embedding-provider';

/**
 * Tiny deterministic embedding provider for tests. Maps content keywords to
 * fixed orthogonal-ish vectors so cosine similarity is fully predictable.
 * No randomness, no I/O.
 */
class StubProvider implements IEmbeddingProvider {
  public embedCalls: string[] = [];
  public failOn = new Set<string>();

  getName() {
    return 'stub';
  }
  getDimensions() {
    return 3;
  }
  async embed(text: string): Promise<EmbeddingResult> {
    this.embedCalls.push(text);
    if (this.failOn.has(text)) throw new Error(`stub fail: ${text}`);
    return {
      text,
      vector: this.vectorFor(text),
      model: 'stub',
      timestamp: Date.now(),
    };
  }
  async embedBatch(texts: string[]): Promise<BatchEmbeddingResult> {
    const embeddings = await Promise.all(texts.map((t) => this.embed(t)));
    return { embeddings, batchSize: texts.length, model: 'stub' };
  }
  similarity(a: number[], b: number[]): number {
    let dot = 0,
      na = 0,
      nb = 0;
    for (let i = 0; i < a.length; i++) {
      dot += a[i] * b[i];
      na += a[i] * a[i];
      nb += b[i] * b[i];
    }
    return na && nb ? dot / (Math.sqrt(na) * Math.sqrt(nb)) : 0;
  }
  findSimilar() {
    return [];
  }
  async healthCheck() {
    return true;
  }

  // Keyword-based vector: text containing "apple" → [1,0,0]; "banana" → [0,1,0];
  // "cherry" → [0,0,1]; else → tiny noise-free zero-ish.
  private vectorFor(text: string): number[] {
    const lower = text.toLowerCase();
    if (lower.includes('apple')) return [1, 0, 0];
    if (lower.includes('banana')) return [0, 1, 0];
    if (lower.includes('cherry')) return [0, 0, 1];
    return [0.01, 0.01, 0.01];
  }
}

describe('NeuralEngramSystem.recallSemantic (item 12)', () => {
  let brain: NeuralEngramSystem;

  beforeEach(() => {
    resetEmbeddingProvider();
    brain = new NeuralEngramSystem();
  });

  afterEach(() => {
    brain.destroy();
    resetEmbeddingProvider();
  });

  describe('MemoryEngram.embedding field', () => {
    it('is unset at write time (lazy contract — embedding is NOT generated by remember())', () => {
      const stub = new StubProvider();
      setEmbeddingProvider(stub);

      const engram = brain.remember('apple pie recipe');

      expect(engram.embedding == null || engram.embedding.length === 0).toBe(
        true
      );
      // remember() must not call the embedding provider — that's the whole
      // point of "lazy": keep the hot write path fast.
      expect(stub.embedCalls).toEqual([]);
    });
  });

  describe('provider gating', () => {
    it('returns [] when no embedding provider is configured', async () => {
      brain.remember('apple pie');
      brain.remember('banana bread');

      const hits = await brain.recallSemantic('apple');

      expect(hits).toEqual([]);
    });
  });

  describe('cosine recall', () => {
    it('ranks engrams by semantic similarity to the query', async () => {
      const stub = new StubProvider();
      setEmbeddingProvider(stub);

      brain.remember('apple pie recipe');
      brain.remember('banana bread loaf');
      brain.remember('cherry tart');

      const hits = await brain.recallSemantic('apple');

      // First hit must be the apple engram (cosine 1 against [1,0,0]);
      // banana + cherry are orthogonal (cosine 0) so they trail.
      expect(hits.length).toBeGreaterThanOrEqual(1);
      expect(hits[0].content).toMatch(/apple/i);
    });
  });

  describe('lazy generation + caching', () => {
    it('does not re-embed engram contents on repeated recalls (cache hit)', async () => {
      const stub = new StubProvider();
      setEmbeddingProvider(stub);

      brain.remember('apple pie');
      brain.remember('banana bread');

      await brain.recallSemantic('apple');
      await brain.recallSemantic('apple');

      // The engram contents must be embedded exactly once across both
      // recalls — that's the lazy-cache spec. Queries DO get embedded each
      // call (and once per hemisphere), so we filter those out.
      const engramEmbeds = stub.embedCalls.filter(
        (t) => t === 'apple pie' || t === 'banana bread'
      );
      expect(engramEmbeds.sort()).toEqual(['apple pie', 'banana bread']);
    });

    it('caches the embedding on the engram held in working memory', async () => {
      const stub = new StubProvider();
      setEmbeddingProvider(stub);

      const original = brain.remember('apple pie');
      expect(
        original.embedding == null || original.embedding.length === 0
      ).toBe(true);

      await brain.recallSemantic('apple');

      // FrontalCortex.hold() clones the engram, so the cache lives on the
      // slot's engram (the in-memory copy), not on the reference returned by
      // remember(). That's intentional — FrontalCortex is volatile by design.
      const slotEngram = brain.frontalCortex
        .getState()
        .engrams.find((e) => e.id === original.id);
      expect(slotEngram).toBeDefined();
      expect(Array.isArray(slotEngram!.embedding)).toBe(true);
      expect(slotEngram!.embedding!.length).toBe(3);
    });
  });

  describe('failure isolation', () => {
    it('skips an engram whose embed throws and still returns the others', async () => {
      const stub = new StubProvider();
      stub.failOn.add('poison content');
      setEmbeddingProvider(stub);

      brain.remember('apple pie');
      brain.remember('poison content');
      brain.remember('cherry tart');

      // Must not throw — one bad engram cannot poison the whole recall.
      const hits = await brain.recallSemantic('apple');

      expect(hits.length).toBeGreaterThanOrEqual(1);
      expect(hits.some((h) => h.content === 'poison content')).toBe(false);
      expect(hits[0].content).toMatch(/apple/i);
    });

    it('returns [] when the query embed itself fails (caller falls back)', async () => {
      const stub = new StubProvider();
      stub.failOn.add('apple');
      setEmbeddingProvider(stub);

      brain.remember('apple pie');

      const hits = await brain.recallSemantic('apple');

      expect(hits).toEqual([]);
    });
  });

  describe('hemisphere coverage', () => {
    it('searches both working memory and the consolidation queue, de-duped by id', async () => {
      const stub = new StubProvider();
      setEmbeddingProvider(stub);

      const working = brain.remember('apple pie working');
      // Stage a second engram directly into the consolidation queue so it
      // lives only in hippocampus, not frontal cortex.
      const staged = brain.remember('apple sauce staged');
      brain.hippocampus.stage(staged);

      const hits = await brain.recallSemantic('apple');
      const ids = hits.map((h) => h.id);

      expect(ids).toContain(working.id);
      expect(ids).toContain(staged.id);
      // De-dup: staged engram is in BOTH working memory and the queue, but
      // must appear exactly once in the merged result.
      expect(ids.filter((id) => id === staged.id).length).toBe(1);
    });
  });
});
