#!/bin/bash
# ============================================================================
# Molly-Core — Paste Your API Keys
#
# Usage: npm run setup-keys
#
# This script asks you to paste two keys, one at a time.
# That's it. No GitHub settings pages, no curl commands.
#
# Key 1: GOOGLE_GENAI_API_KEY  (your Gemini API key)
# Key 2: FIREBASE_SERVICE_ACCOUNT_JSON  (your Firebase service account)
#
# After you paste them, Molly can think and remember.
# ============================================================================

set -e

ENV_FILE=".env.local"

# If running in a path like /workspaces/Molly-Core, use that
if [ -d "/workspaces/Molly-Core" ] && [ "$CODESPACES" = "true" ]; then
  ENV_FILE="/workspaces/Molly-Core/.env.local"
fi

# ── Helper: safely set a key in .env.local ──
# Removes any existing line for the key (commented or not), then appends.
# Uses grep + printf to avoid sed escaping issues with JSON/special chars.
set_env_key() {
  local KEY_NAME="$1"
  local KEY_VALUE="$2"
  local FILE="$3"

  # Remove existing lines (both active and commented)
  if [ -f "$FILE" ]; then
    grep -v "^#\{0,1\} \{0,\}${KEY_NAME}=" "$FILE" > "${FILE}.tmp" || true
    mv "${FILE}.tmp" "$FILE"
  fi

  # Append the new value
  printf '%s=%s\n' "$KEY_NAME" "$KEY_VALUE" >> "$FILE"
}

echo ""
echo "============================================"
echo "  Molly-Core — API Key Setup"
echo "  Just paste your keys when prompted."
echo "  Values are NOT displayed on screen."
echo "============================================"
echo ""

# Create .env.local if it doesn't exist yet
if [ ! -f "$ENV_FILE" ]; then
  cat > "$ENV_FILE" << 'HEADER'
# Molly-Core environment — generated by npm run setup-keys
HEADER
  echo "[Setup] Created $ENV_FILE"
  echo ""
fi

# ── Key 1: Gemini API Key ──────────────────────────
echo "[1/2] GOOGLE_GENAI_API_KEY"
echo ""
echo "  Where to get it:"
echo "    → https://aistudio.google.com/app/apikey"
echo ""
echo "  Paste your Gemini API key and press Enter:"
# Note: -rs hides input from screen. Variable is cleared at script end.
read -rs GEMINI_KEY
echo ""

if [ -n "$GEMINI_KEY" ]; then
  set_env_key "GOOGLE_GENAI_API_KEY" "$GEMINI_KEY" "$ENV_FILE"
  echo "  ✅ Gemini key saved"
else
  echo "  ⏭  Skipped (no input)"
fi

echo ""

# ── Key 2: Firebase Service Account ────────────────
echo "[2/2] FIREBASE_SERVICE_ACCOUNT_JSON"
echo ""
echo "  Where to get it:"
echo "    → Firebase Console → Project Settings"
echo "    → Service Accounts → Generate New Private Key"
echo "    → Open the downloaded JSON file"
echo "    → Copy the ENTIRE contents (it's one long line)"
echo ""
echo "  Paste the Firebase JSON and press Enter:"
# Note: -rs hides input from screen. Variable is cleared at script end.
read -rs FIREBASE_JSON
echo ""

if [ -n "$FIREBASE_JSON" ]; then
  set_env_key "FIREBASE_SERVICE_ACCOUNT_JSON" "$FIREBASE_JSON" "$ENV_FILE"
  echo "  ✅ Firebase service account saved"
else
  echo "  ⏭  Skipped (no input)"
fi

echo ""
echo "============================================"
echo "  Done! Your keys are saved in .env.local"
echo ""
echo "  Now run:  npm run dev"
echo "  Molly will start on port 9002."
echo "============================================"
echo ""

# Clear sensitive variables from memory
unset GEMINI_KEY FIREBASE_JSON
